### ISSUE TITLE
使用inference.py推理时发生错误

### ISSUE THREAD

**Issue by yinyihang3720** [lianqi1008/Control-GIC#1]
作者您好，我在使用Control-GIC压缩一张来自COCO2017数据集的图片（分辨率640x427）时，发生了如下错误：

Traceback (most recent call last):
  File "Control-GIC-main/inference.py", line 178, in <module>
    main()
  File "Control-GIC/inference.py", line 163, in main
    x_rec, bpp, partition_map = model.compress(x, opt.output_dir, h_string, h_mask, save_img=True)
  File "Control-GIC/CGIC/models/model.py", line 207, in compress
    quant, diff, grain_indices, grain_mask, ind, _, mode = self.encode(input)
  File "Control-GIC/CGIC/models/model.py", line 100, in encode
    x_entropy_p8 = self.entropy_calculation_p8(x)
  File "anaconda3/envs/CGIC/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "Control-GIC/CGIC/models/model.py", line 449, in forward
    unfolded_images = torch.reshape(unfolded_images.unsqueeze(2),
RuntimeError: shape '[4270, 64]' is invalid for input of size 271360

这个错误似乎和输入图片的分辨率有关，请问当前版本的程序是否对输入图片的分辨率或者长宽比例有限制？或者是需要修改config_inference文件？

恳请回复，感谢。

**Comment by lianqi1008** [comment]
你好，Control-GIC最粗粒度需要对图像下采样32倍，所以输入图像分辨率需要是32的倍数，将inference.py第57行对图像的crop取消注释即可。

**Comment by lianqi1008** [comment]
> 作者您好，我在使用Control-GIC压缩一张来自COCO2017数据集的图片（分辨率640x427）时，发生了如下错误：
> 
> Traceback (most recent call last): File "Control-GIC-main/inference.py", line 178, in main() File "Control-GIC/inference.py", line 163, in main x_rec, bpp, partition_map = model.compress(x, opt.output_dir, h_string, h_mask, save_img=True) File "Control-GIC/CGIC/models/model.py", line 207, in compress quant, diff, grain_indices, grain_mask, ind, _, mode = self.encode(input) File "Control-GIC/CGIC/models/model.py", line 100, in encode x_entropy_p8 = self.entropy_calculation_p8(x) File "anaconda3/envs/CGIC/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl return forward_call(*input, **kwargs) File "Control-GIC/CGIC/models/model.py", line 449, in forward unfolded_images = torch.reshape(unfolded_images.unsqueeze(2), RuntimeError: shape '[4270, 64]' is invalid for input of size 271360
> 
> 这个错误似乎和输入图片的分辨率有关，请问当前版本的程序是否对输入图片的分辨率或者长宽比例有限制？或者是需要修改config_inference文件？
> 
> 恳请回复，感谢。

你好，Control-GIC最粗粒度需要对图像下采样32倍，所以输入图像分辨率需要是32的倍数，将inference.py第57行对图像的crop取消注释即可。
